package com.setruth.jetpackcomposemviframework.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006876)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA0EFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F25)
val md_theme_light_secondary = Color(0xFF4A6267)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE7ED)
val md_theme_light_onSecondaryContainer = Color(0xFF051F23)
val md_theme_light_tertiary = Color(0xFF545D7E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDBE1FF)
val md_theme_light_onTertiaryContainer = Color(0xFF101A37)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6FFF1)
val md_theme_light_onBackground = Color(0xFF002107)
val md_theme_light_surface = Color(0xFFF6FFF1)
val md_theme_light_onSurface = Color(0xFF002107)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val md_theme_light_outline = Color(0xFF6F797B)
val md_theme_light_inverseOnSurface = Color(0xFFC6FFC6)
val md_theme_light_inverseSurface = Color(0xFF003912)
val md_theme_light_inversePrimary = Color(0xFF51D7EE)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006876)
val md_theme_light_outlineVariant = Color(0xFFBFC8CA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF51D7EE)
val md_theme_dark_onPrimary = Color(0xFF00363E)
val md_theme_dark_primaryContainer = Color(0xFF004E59)
val md_theme_dark_onPrimaryContainer = Color(0xFFA0EFFF)
val md_theme_dark_secondary = Color(0xFFB1CBD1)
val md_theme_dark_onSecondary = Color(0xFF1C3439)
val md_theme_dark_secondaryContainer = Color(0xFF334B4F)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE7ED)
val md_theme_dark_tertiary = Color(0xFFBCC5EB)
val md_theme_dark_onTertiary = Color(0xFF262F4D)
val md_theme_dark_tertiaryContainer = Color(0xFF3C4665)
val md_theme_dark_onTertiaryContainer = Color(0xFFDBE1FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF002107)
val md_theme_dark_onBackground = Color(0xFFA4F5A9)
val md_theme_dark_surface = Color(0xFF002107)
val md_theme_dark_onSurface = Color(0xFFA4F5A9)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
val md_theme_dark_outline = Color(0xFF899295)
val md_theme_dark_inverseOnSurface = Color(0xFF002107)
val md_theme_dark_inverseSurface = Color(0xFFA4F5A9)
val md_theme_dark_inversePrimary = Color(0xFF006876)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF51D7EE)
val md_theme_dark_outlineVariant = Color(0xFF3F484A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF007B8B)
